<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Add refstudent');

require 'components/get_listview_referrer.php';

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_submit']);
    require 'components/query_string_standard.php';
    require 'subclasses/refstudent.php';
    $dbh_refstudent = new refstudent;

    $object_name = 'dbh_refstudent';
    require 'components/create_form_data.php';
    extract($arr_form_data);

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_refstudent.php?$query_string");
    }


    if($_POST['btn_submit'])
    {
        log_action('Pressed submit button');

        $message .= $dbh_refstudent->sanitize($arr_form_data)->lst_error;
        extract($arr_form_data);

        if($dbh_refstudent->check_uniqueness($arr_form_data)->is_unique)
        {
            //Good, no duplicate in database
        }
        else
        {
            $message = "Record already exists with the same primary identifiers!";
        }

        if($message=="")
        {
            $dbh_refstudent->add($arr_form_data);
            
            require_once 'subclasses/xrefstudentschedule.php';
            $dbh_refstudent = new xrefstudentschedule;
            for($a=0; $a<$xrefstudentschedule_count;$a++)
            {
                $cf_xrefstudentschedule_date[$a] = $cf_xrefstudentschedule_date_year[$a] . '-' . $cf_xrefstudentschedule_date_month[$a] . '-' . $cf_xrefstudentschedule_date_day[$a];
               
                $param = array(
                               'subject_offering_id'=>$cf_xrefstudentschedule_subject_offering_id[$a],
                               'student_id'=>$student_id,
                               'enrollment_status'=>$cf_xrefstudentschedule_enrollment_status[$a],
                               'date'=>$cf_xrefstudentschedule_date[$a],
                               'term_id'=>$cf_xrefstudentschedule_term_id[$a],
                               'subject_code'=>$cf_xrefstudentschedule_subject_code[$a]
                              );
                $dbh_refstudent->add($param);
            }

            require_once 'subclasses/log_info.php';
            $dbh_refstudent = new log_info;
            for($a=0; $a<$log_info_count;$a++)
            {
                $cf_log_info_date[$a] = $cf_log_info_date_year[$a] . '-' . $cf_log_info_date_month[$a] . '-' . $cf_log_info_date_day[$a];
               
                $param = array(
                               'date'=>$cf_log_info_date[$a],
                               'time'=>$cf_log_info_time[$a],
                               'complaints'=>$cf_log_info_complaints[$a],
                               'medicine_id'=>$cf_log_info_medicine_id[$a],
                               'student_id'=>$student_id,
                               'emp_id'=>$cf_log_info_emp_id[$a]
                              );
                $dbh_refstudent->add($param);
            }


            redirect("listview_refstudent.php?$query_string");
        }
    }
}
require 'subclasses/refstudent_html.php';
$html = new refstudent_html;
$html->draw_header('Add %%', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);
$html->draw_controls('add');

$html->draw_footer();