<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Add refstudentclearance');

require 'components/get_listview_referrer.php';

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_submit']);
    require 'components/query_string_standard.php';
    require 'subclasses/refstudentclearance.php';
    $dbh_refstudentclearance = new refstudentclearance;

    $object_name = 'dbh_refstudentclearance';
    require 'components/create_form_data.php';
    extract($arr_form_data);

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_refstudentclearance.php?$query_string");
    }

     if($_POST)
    {
    $dbh = cobalt_load_class('refstudent');
   
    $result = $dbh->execute_query("SELECT student_first_name, student_middle_name, student_last_name FROM refstudent WHERE student_id ='".$_POST['student_id']."'")->result;
       
   $row = $result->fetch_assoc();
   

   $student_name = $row['student_first_name'].' '.$row['student_middle_name'].' '.$row['student_last_name'];

   // $emp_id = $_SESSION['last_name'] . ', ' . $_SESSION['first_name'] . ' ' . $_SESSION['middle_name'];
  

    }


    if($_POST['btn_submit'])
    {
        log_action('Pressed submit button');

        $message .= $dbh_refstudentclearance->sanitize($arr_form_data)->lst_error;
        extract($arr_form_data);

        if($dbh_refstudentclearance->check_uniqueness($arr_form_data)->is_unique)
        {
            //Good, no duplicate in database
        }
        else
        {
            $message = "Record already exists with the same primary identifiers!";
        }

        if($message=="")
        {
            $dbh_refstudentclearance->add($arr_form_data);
            

            redirect("listview_refstudentclearance.php?$query_string");
        }
    }
}
require 'subclasses/refstudentclearance_html.php';
$html = new refstudentclearance_html;
$html->draw_header('Add %%', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

init_var($student_name);
$html->fields['student_id']['companion'] = '<input type="text" name="student_name" placeholder="patient name" value="'.$student_name.'">';

$html->draw_controls('add');

$html->draw_footer();