<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Edit dept');

if(isset($_GET['dept_id']))
{
    $dept_id = urldecode($_GET['dept_id']);
    require 'form_data_dept.php';

}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_submit']);
    require 'components/query_string_standard.php';
    require 'subclasses/dept.php';
    $dbh_dept = new dept;

    $object_name = 'dbh_dept';
    require 'components/create_form_data.php';

    extract($arr_form_data);

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_dept.php?$query_string");
    }


    if($_POST['btn_submit'])
    {
        log_action('Pressed submit button');

        $message .= $dbh_dept->sanitize($arr_form_data)->lst_error;
        extract($arr_form_data);

        if($dbh_dept->check_uniqueness_for_editing($arr_form_data)->is_unique)
        {
            //Good, no duplicate in database
        }
        else
        {
            $message = "Record already exists with the same primary identifiers!";
        }

        if($message=="")
        {
            require_once 'subclasses/refstudentclearance.php';
            $dbh_refstudentclearance = new refstudentclearance;
            $dbh_refstudentclearance->delete_many($arr_form_data);

            for($a=0; $a<$refstudentclearance_count;$a++)
            {
                $cf_refstudentclearance_date[$a] = $cf_refstudentclearance_date_year[$a] . '-' . $cf_refstudentclearance_date_month[$a] . '-' . $cf_refstudentclearance_date_day[$a];
               
                $param = array(
                               'term_id'=>$cf_refstudentclearance_term_id[$a],
                               'date'=>$cf_refstudentclearance_date[$a],
                               'student_id'=>$cf_refstudentclearance_student_id[$a],
                               'remarks'=>$cf_refstudentclearance_remarks[$a],
                               'is_clear'=>$cf_refstudentclearance_is_clear[$a],
                               'emp_id'=>$cf_refstudentclearance_emp_id[$a],
                               'dept_id'=>$dept_id
                              );
                $dbh_refstudentclearance->add($param);
            }


            $dbh_dept->edit($arr_form_data);

            redirect("listview_dept.php?$query_string");
        }
    }
}
require 'subclasses/dept_html.php';
$html = new dept_html;
$html->draw_header('Edit %%', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);
$html->draw_hidden('dept_id');

$html->draw_controls('edit');

$html->draw_footer();