<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Edit log detail');

if(isset($_GET['log_detail_id']))
{
    $log_detail_id = urldecode($_GET['log_detail_id']);
    require 'form_data_log_detail.php';

}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_submit']);
    require 'components/query_string_standard.php';
    require 'subclasses/log_detail.php';
    $dbh_log_detail = new log_detail;

    $object_name = 'dbh_log_detail';
    require 'components/create_form_data.php';

    extract($arr_form_data);

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_log_detail.php?$query_string");
    }


    if($_POST['btn_submit'])
    {
        log_action('Pressed submit button');

        $message .= $dbh_log_detail->sanitize($arr_form_data)->lst_error;
        extract($arr_form_data);

        if($dbh_log_detail->check_uniqueness_for_editing($arr_form_data)->is_unique)
        {
            //Good, no duplicate in database
        }
        else
        {
            $message = "Record already exists with the same primary identifiers!";
        }

        if($message=="")
        {

            $dbh_log_detail->edit($arr_form_data);

            redirect("listview_log_detail.php?$query_string");
        }
    }
}
require 'subclasses/log_detail_html.php';
$html = new log_detail_html;
$html->draw_header('Edit %%', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);
$html->draw_hidden('log_detail_id');

$html->draw_controls('edit');

$html->draw_footer();