<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Delete log dtl');

if(isset($_GET['log_dtl_id']))
{
    $log_dtl_id = urldecode($_GET['log_dtl_id']);
    require_once 'form_data_log_dtl.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_delete']);
    require 'components/query_string_standard.php';

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_log_dtl.php?$query_string");
    }

    elseif($_POST['btn_delete'])
    {
        log_action('Pressed delete button');
        require_once 'subclasses/log_dtl.php';
        $dbh_log_dtl = new log_dtl;

        $object_name = 'dbh_log_dtl';
        require 'components/create_form_data.php';

        require_once 'subclasses/log_info.php';
        $dbh_log_info = new log_info;
        $dbh_log_info->delete_many($arr_form_data);


        $dbh_log_dtl->delete($arr_form_data);

        redirect("listview_log_dtl.php?$query_string");
    }
}
require 'subclasses/log_dtl_html.php';
$html = new log_dtl_html;
$html->draw_header('Delete %%', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('log_dtl_id');

$html->detail_view = TRUE;
$html->draw_controls('delete');

$html->draw_footer();