<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Delete log detail');

if(isset($_GET['log_detail_id']))
{
    $log_detail_id = urldecode($_GET['log_detail_id']);
    require_once 'form_data_log_detail.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_delete']);
    require 'components/query_string_standard.php';

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_log_detail.php?$query_string");
    }

    elseif($_POST['btn_delete'])
    {
        log_action('Pressed delete button');
        require_once 'subclasses/log_detail.php';
        $dbh_log_detail = new log_detail;

        $object_name = 'dbh_log_detail';
        require 'components/create_form_data.php';


        $dbh_log_detail->delete($arr_form_data);

        redirect("listview_log_detail.php?$query_string");
    }
}
require 'subclasses/log_detail_html.php';
$html = new log_detail_html;
$html->draw_header('Delete %%', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('log_detail_id');

$html->detail_view = TRUE;
$html->draw_controls('delete');

$html->draw_footer();