<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Edit log dtl');

if(isset($_GET['log_dtl_id']))
{
    $log_dtl_id = urldecode($_GET['log_dtl_id']);
    require 'form_data_log_dtl.php';

}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_submit']);
    require 'components/query_string_standard.php';
    require 'subclasses/log_dtl.php';
    $dbh_log_dtl = new log_dtl;

    $object_name = 'dbh_log_dtl';
    require 'components/create_form_data.php';

    extract($arr_form_data);

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_log_dtl.php?$query_string");
    }


    if($_POST['btn_submit'])
    {
        log_action('Pressed submit button');

        $message .= $dbh_log_dtl->sanitize($arr_form_data)->lst_error;
        extract($arr_form_data);

        if($dbh_log_dtl->check_uniqueness_for_editing($arr_form_data)->is_unique)
        {
            //Good, no duplicate in database
        }
        else
        {
            $message = "Record already exists with the same primary identifiers!";
        }

        if($message=="")
        {
            require_once 'subclasses/log_info.php';
            $dbh_log_info = new log_info;
            $dbh_log_info->delete_many($arr_form_data);

            for($a=0; $a<$log_info_count;$a++)
            {
                $cf_log_info_date[$a] = $cf_log_info_date_year[$a] . '-' . $cf_log_info_date_month[$a] . '-' . $cf_log_info_date_day[$a];
               
                $param = array(
                               'date'=>$cf_log_info_date[$a],
                               'time'=>$cf_log_info_time[$a],
                               'complaints'=>$cf_log_info_complaints[$a],
                               'log_dtl_id'=>$log_dtl_id,
                               'student_id'=>$cf_log_info_student_id[$a],
                               'emp_id'=>$cf_log_info_emp_id[$a]
                              );
                $dbh_log_info->add($param);
            }


            $dbh_log_dtl->edit($arr_form_data);

            redirect("listview_log_dtl.php?$query_string");
        }
    }
}
require 'subclasses/log_dtl_html.php';
$html = new log_dtl_html;
$html->draw_header('Edit %%', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);
$html->draw_hidden('log_dtl_id');

$html->draw_controls('edit');

$html->draw_footer();