<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Delete refstudentfamily');

if(isset($_GET['family_id']))
{
    $family_id = urldecode($_GET['family_id']);
    require_once 'form_data_refstudentfamily.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_delete']);
    require 'components/query_string_standard.php';

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_refstudentfamily.php?$query_string");
    }

    elseif($_POST['btn_delete'])
    {
        log_action('Pressed delete button');
        require_once 'subclasses/refstudentfamily.php';
        $dbh_refstudentfamily = new refstudentfamily;

        $object_name = 'dbh_refstudentfamily';
        require 'components/create_form_data.php';


        $dbh_refstudentfamily->delete($arr_form_data);

        redirect("listview_refstudentfamily.php?$query_string");
    }
}
require 'subclasses/refstudentfamily_html.php';
$html = new refstudentfamily_html;
$html->draw_header('Delete %%', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('family_id');

$html->detail_view = TRUE;
$html->draw_controls('delete');

$html->draw_footer();