<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Add employee');

require 'components/get_listview_referrer.php';

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_submit']);
    require 'components/query_string_standard.php';
    require 'subclasses/employee.php';
    $dbh_employee = new employee;

    $object_name = 'dbh_employee';
    require 'components/create_form_data.php';
    extract($arr_form_data);

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_employee.php?$query_string");
    }


    if($_POST['btn_submit'])
    {
        log_action('Pressed submit button');

        $message .= $dbh_employee->sanitize($arr_form_data)->lst_error;
        extract($arr_form_data);

        if($dbh_employee->check_uniqueness($arr_form_data)->is_unique)
        {
            //Good, no duplicate in database
        }
        else
        {
            $message = "Record already exists with the same primary identifiers!";
        }

        if($message=="")
        {
            $dbh_employee->add($arr_form_data);
            $employee_id = $dbh_employee->auto_id;
            require_once 'subclasses/employee_license.php';
            $dbh_employee = new employee_license;
            for($a=0; $a<$employee_license_count;$a++)
            {
                $cf_employee_license_date_acquired[$a] = $cf_employee_license_date_acquired_year[$a] . '-' . $cf_employee_license_date_acquired_month[$a] . '-' . $cf_employee_license_date_acquired_day[$a];
               
                $param = array(
                               'employee_id'=>$employee_id,
                               'license_name'=>$cf_employee_license_license_name[$a],
                               'date_acquired'=>$cf_employee_license_date_acquired[$a],
                               'description'=>$cf_employee_license_description[$a]
                              );
                $dbh_employee->add($param);
            }

            require_once 'subclasses/employee_family.php';
            $dbh_employee = new employee_family;
            for($a=0; $a<$employee_family_count;$a++)
            {
                $cf_employee_family_family_birthdate[$a] = $cf_employee_family_family_birthdate_year[$a] . '-' . $cf_employee_family_family_birthdate_month[$a] . '-' . $cf_employee_family_family_birthdate_day[$a];
               
                $param = array(
                               'employee_id'=>$employee_id,
                               'family_first_name'=>$cf_employee_family_family_first_name[$a],
                               'family_middle_name'=>$cf_employee_family_family_middle_name[$a],
                               'family_last_name'=>$cf_employee_family_family_last_name[$a],
                               'family_birthdate'=>$cf_employee_family_family_birthdate[$a],
                               'family_relation'=>$cf_employee_family_family_relation[$a]
                              );
                $dbh_employee->add($param);
            }

            require_once 'subclasses/employee_work_experience.php';
            $dbh_employee = new employee_work_experience;
            for($a=0; $a<$employee_work_experience_count;$a++)
            {
                
                $param = array(
                               'employee_id'=>$employee_id,
                               'company'=>$cf_employee_work_experience_company[$a],
                               'period'=>$cf_employee_work_experience_period[$a],
                               'position'=>$cf_employee_work_experience_position[$a]
                              );
                $dbh_employee->add($param);
            }

            require_once 'subclasses/employee_reference.php';
            $dbh_employee = new employee_reference;
            for($a=0; $a<$employee_reference_count;$a++)
            {
                
                $param = array(
                               'employee_id'=>$employee_id,
                               'name'=>$cf_employee_reference_name[$a],
                               'company'=>$cf_employee_reference_company[$a],
                               'position'=>$cf_employee_reference_position[$a],
                               'contact_no'=>$cf_employee_reference_contact_no[$a],
                               'email'=>$cf_employee_reference_email[$a]
                              );
                $dbh_employee->add($param);
            }

            require_once 'subclasses/employee_education.php';
            $dbh_employee = new employee_education;
            for($a=0; $a<$employee_education_count;$a++)
            {
                
                $param = array(
                               'employee_id'=>$employee_id,
                               'level'=>$cf_employee_education_level[$a],
                               'school'=>$cf_employee_education_school[$a],
                               'period'=>$cf_employee_education_period[$a],
                               'awards'=>$cf_employee_education_awards[$a]
                              );
                $dbh_employee->add($param);
            }


            redirect("listview_employee.php?$query_string");
        }
    }
}
require 'subclasses/employee_html.php';
$html = new employee_html;
$html->draw_header('Add %%', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);
$html->draw_controls('add');

$html->draw_footer();