<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Delete employee');

if(isset($_GET['employee_id']))
{
    $employee_id = urldecode($_GET['employee_id']);
    require_once 'form_data_employee.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_delete']);
    require 'components/query_string_standard.php';

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_employee.php?$query_string");
    }

    elseif($_POST['btn_delete'])
    {
        log_action('Pressed delete button');
        require_once 'subclasses/employee.php';
        $dbh_employee = new employee;

        $object_name = 'dbh_employee';
        require 'components/create_form_data.php';

        require_once 'subclasses/employee_license.php';
        $dbh_employee_license = new employee_license;
        $dbh_employee_license->delete_many($arr_form_data);

        require_once 'subclasses/employee_family.php';
        $dbh_employee_family = new employee_family;
        $dbh_employee_family->delete_many($arr_form_data);

        require_once 'subclasses/employee_work_experience.php';
        $dbh_employee_work_experience = new employee_work_experience;
        $dbh_employee_work_experience->delete_many($arr_form_data);

        require_once 'subclasses/employee_reference.php';
        $dbh_employee_reference = new employee_reference;
        $dbh_employee_reference->delete_many($arr_form_data);

        require_once 'subclasses/employee_education.php';
        $dbh_employee_education = new employee_education;
        $dbh_employee_education->delete_many($arr_form_data);


        $dbh_employee->delete($arr_form_data);

        redirect("listview_employee.php?$query_string");
    }
}
require 'subclasses/employee_html.php';
$html = new employee_html;
$html->draw_header('Delete %%', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('employee_id');

$html->detail_view = TRUE;
$html->draw_controls('delete');

$html->draw_footer();