<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Delete medicine receiving');

if(isset($_GET['medicine_count_id']))
{
    $medicine_count_id = urldecode($_GET['medicine_count_id']);
    require_once 'form_data_medicine_receiving.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_delete']);
    require 'components/query_string_standard.php';

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_medicine_receiving.php?$query_string");
    }

    elseif($_POST['btn_delete'])
    {
        log_action('Pressed delete button');
        require_once 'subclasses/medicine_receiving.php';
        $dbh_medicine_receiving = new medicine_receiving;

        $object_name = 'dbh_medicine_receiving';
        require 'components/create_form_data.php';


        $dbh_medicine_receiving->delete($arr_form_data);

        redirect("listview_medicine_receiving.php?$query_string");
    }
}
require 'subclasses/medicine_receiving_html.php';
$html = new medicine_receiving_html;
$html->draw_header('Delete %%', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('medicine_count_id');

$html->detail_view = TRUE;
$html->draw_controls('delete');

$html->draw_footer();