<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Add transaction header');

require 'components/get_listview_referrer.php';

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_submit']);
    require 'components/query_string_standard.php';
    require 'subclasses/transaction_header.php';
    $dbh_transaction_header = new transaction_header;

    $object_name = 'dbh_transaction_header';
    require 'components/create_form_data.php';
    extract($arr_form_data);

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_transaction_header.php?$query_string");
    }


    if($_POST['btn_submit'])
    {
        log_action('Pressed submit button');

        $message .= $dbh_transaction_header->sanitize($arr_form_data)->lst_error;
        extract($arr_form_data);

        if($dbh_transaction_header->check_uniqueness($arr_form_data)->is_unique)
        {
            //Good, no duplicate in database
        }
        else
        {
            $message = "Record already exists with the same primary identifiers!";
        }

        if($message=="")
        {
            $dbh_transaction_header->add($arr_form_data);
            
            require_once 'subclasses/transaction_details.php';
            $dbh_transaction_header = new transaction_details;
            for($a=0; $a<$transaction_details_count;$a++)
            {
                
                $param = array(
                               'transaction_header_id'=>$transaction_header_id,
                               'product_id'=>$cf_transaction_details_product_id[$a],
                               'unit_price'=>$cf_transaction_details_unit_price[$a],
                               'quantity'=>$cf_transaction_details_quantity[$a],
                               'net_amount'=>$cf_transaction_details_net_amount[$a],
                               'discount_type'=>$cf_transaction_details_discount_type[$a],
                               'discount_value'=>$cf_transaction_details_discount_value[$a]
                              );
                $dbh_transaction_header->add($param);
            }


            redirect("listview_transaction_header.php?$query_string");
        }
    }
}
require 'subclasses/transaction_header_html.php';
$html = new transaction_header_html;
$html->draw_header('Add %%', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);
$html->draw_controls('add');

$html->draw_footer();