<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Delete transaction header');

if(isset($_GET['transaction_header_id']))
{
    $transaction_header_id = urldecode($_GET['transaction_header_id']);
    require_once 'form_data_transaction_header.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_delete']);
    require 'components/query_string_standard.php';

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_transaction_header.php?$query_string");
    }

    elseif($_POST['btn_delete'])
    {
        log_action('Pressed delete button');
        require_once 'subclasses/transaction_header.php';
        $dbh_transaction_header = new transaction_header;

        $object_name = 'dbh_transaction_header';
        require 'components/create_form_data.php';

        require_once 'subclasses/transaction_details.php';
        $dbh_transaction_details = new transaction_details;
        $dbh_transaction_details->delete_many($arr_form_data);


        $dbh_transaction_header->delete($arr_form_data);

        redirect("listview_transaction_header.php?$query_string");
    }
}
require 'subclasses/transaction_header_html.php';
$html = new transaction_header_html;
$html->draw_header('Delete %%', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('transaction_header_id');

$html->detail_view = TRUE;
$html->draw_controls('delete');

$html->draw_footer();