<?php
//****************************************************************************************
//Generated by Cobalt, a rapid application development framework. http://cobalt.jvroig.com
//Cobalt developed by JV Roig (jvroig@jvroig.com)
//****************************************************************************************
require 'path.php';
init_cobalt('Delete required appointment');

if(isset($_GET['required_appointment_id']))
{
    $required_appointment_id = urldecode($_GET['required_appointment_id']);
    require_once 'form_data_required_appointment.php';
}

if(xsrf_guard())
{
    init_var($_POST['btn_cancel']);
    init_var($_POST['btn_delete']);
    require 'components/query_string_standard.php';

    if($_POST['btn_cancel'])
    {
        log_action('Pressed cancel button');
        redirect("listview_required_appointment.php?$query_string");
    }

    elseif($_POST['btn_delete'])
    {
        log_action('Pressed delete button');
        require_once 'subclasses/required_appointment.php';
        $dbh_required_appointment = new required_appointment;

        $object_name = 'dbh_required_appointment';
        require 'components/create_form_data.php';


        $dbh_required_appointment->delete($arr_form_data);

        redirect("listview_required_appointment.php?$query_string");
    }
}
require 'subclasses/required_appointment_html.php';
$html = new required_appointment_html;
$html->draw_header('Delete %%', $message, $message_type);
$html->draw_listview_referrer_info($filter_field_used, $filter_used, $page_from, $filter_sort_asc, $filter_sort_desc);

$html->draw_hidden('required_appointment_id');

$html->detail_view = TRUE;
$html->draw_controls('delete');

$html->draw_footer();