<?php
require_once 'log_info_dd.php';
class log_info_rpt extends reporter
{
    var $tables='';
    var $session_array_name = 'LOG_INFO_REPORT_CUSTOM';
    var $report_title = '%%: Custom Reporting Tool';
    var $html_subclass = 'log_info_html';
    var $data_subclass = 'log_info';
    var $result_page = 'reporter_result_log_info.php';
    var $cancel_page = 'listview_log_info.php';
    var $pdf_reporter_filename = 'reporter_pdfresult_log_info.php';

    function __construct()
    {
        $this->fields        = log_info_dd::load_dictionary();
        $this->relations     = log_info_dd::load_relationships();
        $this->subclasses    = log_info_dd::load_subclass_info();
        $this->table_name    = log_info_dd::$table_name;
        $this->tables        = log_info_dd::$table_name;
        $this->readable_name = log_info_dd::$readable_name;
        $this->get_report_fields();
    }
    function get_custom_join()
    {
        $this->custom_join = 'log_info a LEFT JOIN refstudent b ON a.student_id = b.student_id 
        LEFT JOIN employee c ON a.emp_id = c.emp_id , log_detail d LEFT JOIN medicine e ON d.medicine_id = e.medicine_id';
        return $this;
    }

    function get_report_fields()
    {
        $this->arr_rpt_fields = array('Log ID',
                                      'Date',
                                      'Time',
                                      'Complaints',
                                      'Patient Type',
                                      '[Refstudent] Student ID',
                                      '[Refstudent] Student First Name',
                                      '[Refstudent] Student Middle Name',
                                      '[Refstudent] Student Last Name',
                                      '[Refstudent] Birth Date',
                                      '[Refstudent] Birth Place',
                                      '[Refstudent] Admission Date',
                                      '[Refstudent] Entry Level',
                                      '[Refstudent] Admission Credential',
                                      '[Refstudent] Mail Grades To',
                                      '[Refstudent] Exit Level',
                                      '[Refstudent] Nationality',
                                      '[Refstudent] Gender',
                                      '[Refstudent] Address',
                                      '[Refstudent] Postal Code',
                                      '[Refstudent] Telephone No.',
                                      '[Refstudent] Mobile No.',
                                      '[Refstudent] Email',
                                      '[Refstudent] Religion',
                                      '[Refstudent] Civil Status',
                                      '[Refstudent] Box Num',
                                      '[Employee] Emp ID',
                                      '[Employee] Employee First Name',
                                      '[Employee] Employee Middle Name',
                                      '[Employee] Employee Last Name',
                                      '[Employee] Email',
                                      '[Employee] Employee Status',
                                      '[Employee] Employee Group',
                                      '[Employee] Address',
                                      '[Employee] Postal Code',
                                      '[Employee] Telephone No.',
                                      '[Employee] Mobile Number',
                                      '[Employee] Hiring Date',
                                      '[Employee] Gender',
                                      '[Employee] Civil Status',
                                      '[Employee] Birth Date',
                                      '[Employee] Birth Place',
                                      '[Employee] Religion',
                                      '[Employee] Is Deleted',
                                      '[Employee] ATM',
                                      '[Employee] BDO ATM',
                                      '[Employee] SSS Number',
                                      '[Employee] PhilHealth',
                                      '[Employee] TIN',
                                      '[Employee] PagIbig',
                                      '[Log Detail] Log_detail_id',
                                      '[Log Detail] Log_id',
                                      '[Log Detail] Medicine',
                                      '[Log Detail] Quantity',
                                      '[Medicine] Medicine_id',
                                      '[Medicine] Medicine_name',
                                      '[Medicine] Expiration Date',
                                      );

        $this->arr_rpt_fields_sql = array($this->arr_rpt_fields[0]=>'a.log_id',
                                          $this->arr_rpt_fields[1]=>'a.date',
                                          $this->arr_rpt_fields[2]=>'a.time',
                                          $this->arr_rpt_fields[3]=>'a.complaints',
                                          $this->arr_rpt_fields[4]=>'a.patient_type',
                                          $this->arr_rpt_fields[5]=>'b.student_id',
                                          $this->arr_rpt_fields[6]=>'b.student_first_name',
                                          $this->arr_rpt_fields[7]=>'b.student_middle_name',
                                          $this->arr_rpt_fields[8]=>'b.student_last_name',
                                          $this->arr_rpt_fields[9]=>'b.birth_date',
                                          $this->arr_rpt_fields[10]=>'b.birth_place',
                                          $this->arr_rpt_fields[11]=>'b.admission_date',
                                          $this->arr_rpt_fields[12]=>'b.entry_level',
                                          $this->arr_rpt_fields[13]=>'b.admission_credential',
                                          $this->arr_rpt_fields[14]=>'b.mail_grades_to',
                                          $this->arr_rpt_fields[15]=>'b.exit_level',
                                          $this->arr_rpt_fields[16]=>'b.nationality',
                                          $this->arr_rpt_fields[17]=>'b.gender',
                                          $this->arr_rpt_fields[18]=>'b.address',
                                          $this->arr_rpt_fields[19]=>'b.postal_code',
                                          $this->arr_rpt_fields[20]=>'b.tel_num',
                                          $this->arr_rpt_fields[21]=>'b.mobile_num',
                                          $this->arr_rpt_fields[22]=>'b.email',
                                          $this->arr_rpt_fields[23]=>'b.religion',
                                          $this->arr_rpt_fields[24]=>'b.civil_status',
                                          $this->arr_rpt_fields[25]=>'b.box_num',
                                          $this->arr_rpt_fields[26]=>'c.emp_id',
                                          $this->arr_rpt_fields[27]=>'c.emp_first_name',
                                          $this->arr_rpt_fields[28]=>'c.emp_middle_name',
                                          $this->arr_rpt_fields[29]=>'c.emp_last_name',
                                          $this->arr_rpt_fields[30]=>'c.email',
                                          $this->arr_rpt_fields[31]=>'c.emp_status',
                                          $this->arr_rpt_fields[32]=>'c.emp_group',
                                          $this->arr_rpt_fields[33]=>'c.address',
                                          $this->arr_rpt_fields[34]=>'c.postal_code',
                                          $this->arr_rpt_fields[35]=>'c.tel_num',
                                          $this->arr_rpt_fields[36]=>'c.mobile_num',
                                          $this->arr_rpt_fields[37]=>'c.hiring_date',
                                          $this->arr_rpt_fields[38]=>'c.gender',
                                          $this->arr_rpt_fields[39]=>'c.civil_status',
                                          $this->arr_rpt_fields[40]=>'c.birth_date',
                                          $this->arr_rpt_fields[41]=>'c.birth_place',
                                          $this->arr_rpt_fields[42]=>'c.religion',
                                          $this->arr_rpt_fields[43]=>'c.is_deleted',
                                          $this->arr_rpt_fields[44]=>'c.ATM_num',
                                          $this->arr_rpt_fields[45]=>'c.BDO_ATM_num',
                                          $this->arr_rpt_fields[46]=>'c.SSS_num',
                                          $this->arr_rpt_fields[47]=>'c.PhilHealth_num',
                                          $this->arr_rpt_fields[48]=>'c.TIN_num',
                                          $this->arr_rpt_fields[49]=>'c.PagIbig_num',
                                          $this->arr_rpt_fields[50]=>'d.log_detail_id',
                                          $this->arr_rpt_fields[51]=>'d.log_id',
                                          $this->arr_rpt_fields[52]=>'d.medicine_id',
                                          $this->arr_rpt_fields[53]=>'d.qty',
                                          $this->arr_rpt_fields[54]=>'e.medicine_id',
                                          $this->arr_rpt_fields[55]=>'e.medicine_name',
                                          $this->arr_rpt_fields[56]=>'e.date_expiration',
                                          );

        $this->arr_rpt_column_alignments = array($this->arr_rpt_fields[0]=>'center',
                                                 $this->arr_rpt_fields[1]=>'left',
                                                 $this->arr_rpt_fields[2]=>'left',
                                                 $this->arr_rpt_fields[3]=>'left',
                                                 $this->arr_rpt_fields[4]=>'left',
                                                 $this->arr_rpt_fields[5]=>'center',
                                                 $this->arr_rpt_fields[6]=>'left',
                                                 $this->arr_rpt_fields[7]=>'left',
                                                 $this->arr_rpt_fields[8]=>'left',
                                                 $this->arr_rpt_fields[9]=>'left',
                                                 $this->arr_rpt_fields[10]=>'left',
                                                 $this->arr_rpt_fields[11]=>'left',
                                                 $this->arr_rpt_fields[12]=>'left',
                                                 $this->arr_rpt_fields[13]=>'left',
                                                 $this->arr_rpt_fields[14]=>'left',
                                                 $this->arr_rpt_fields[15]=>'left',
                                                 $this->arr_rpt_fields[16]=>'left',
                                                 $this->arr_rpt_fields[17]=>'left',
                                                 $this->arr_rpt_fields[18]=>'left',
                                                 $this->arr_rpt_fields[19]=>'left',
                                                 $this->arr_rpt_fields[20]=>'left',
                                                 $this->arr_rpt_fields[21]=>'left',
                                                 $this->arr_rpt_fields[22]=>'left',
                                                 $this->arr_rpt_fields[23]=>'left',
                                                 $this->arr_rpt_fields[24]=>'left',
                                                 $this->arr_rpt_fields[25]=>'left',
                                                 $this->arr_rpt_fields[26]=>'center',
                                                 $this->arr_rpt_fields[27]=>'left',
                                                 $this->arr_rpt_fields[28]=>'left',
                                                 $this->arr_rpt_fields[29]=>'left',
                                                 $this->arr_rpt_fields[30]=>'left',
                                                 $this->arr_rpt_fields[31]=>'right',
                                                 $this->arr_rpt_fields[32]=>'right',
                                                 $this->arr_rpt_fields[33]=>'left',
                                                 $this->arr_rpt_fields[34]=>'left',
                                                 $this->arr_rpt_fields[35]=>'left',
                                                 $this->arr_rpt_fields[36]=>'left',
                                                 $this->arr_rpt_fields[37]=>'left',
                                                 $this->arr_rpt_fields[38]=>'left',
                                                 $this->arr_rpt_fields[39]=>'left',
                                                 $this->arr_rpt_fields[40]=>'left',
                                                 $this->arr_rpt_fields[41]=>'left',
                                                 $this->arr_rpt_fields[42]=>'left',
                                                 $this->arr_rpt_fields[43]=>'left',
                                                 $this->arr_rpt_fields[44]=>'left',
                                                 $this->arr_rpt_fields[45]=>'left',
                                                 $this->arr_rpt_fields[46]=>'left',
                                                 $this->arr_rpt_fields[47]=>'left',
                                                 $this->arr_rpt_fields[48]=>'left',
                                                 $this->arr_rpt_fields[49]=>'left',
                                                 $this->arr_rpt_fields[50]=>'left',
                                                 $this->arr_rpt_fields[51]=>'left',
                                                 $this->arr_rpt_fields[52]=>'left',
                                                 $this->arr_rpt_fields[53]=>'left',
                                                 $this->arr_rpt_fields[54]=>'left',
                                                 $this->arr_rpt_fields[55]=>'left',
                                                 $this->arr_rpt_fields[56]=>'left',
                                                 );

        $this->arr_rpt_column_formats = array($this->arr_rpt_fields[0]=>'normal',
                                              $this->arr_rpt_fields[1]=>'normal',
                                              $this->arr_rpt_fields[2]=>'normal',
                                              $this->arr_rpt_fields[3]=>'normal',
                                              $this->arr_rpt_fields[4]=>'normal',
                                              $this->arr_rpt_fields[5]=>'normal',
                                              $this->arr_rpt_fields[6]=>'normal',
                                              $this->arr_rpt_fields[7]=>'normal',
                                              $this->arr_rpt_fields[8]=>'normal',
                                              $this->arr_rpt_fields[9]=>'normal',
                                              $this->arr_rpt_fields[10]=>'normal',
                                              $this->arr_rpt_fields[11]=>'normal',
                                              $this->arr_rpt_fields[12]=>'normal',
                                              $this->arr_rpt_fields[13]=>'normal',
                                              $this->arr_rpt_fields[14]=>'normal',
                                              $this->arr_rpt_fields[15]=>'normal',
                                              $this->arr_rpt_fields[16]=>'normal',
                                              $this->arr_rpt_fields[17]=>'normal',
                                              $this->arr_rpt_fields[18]=>'normal',
                                              $this->arr_rpt_fields[19]=>'normal',
                                              $this->arr_rpt_fields[20]=>'normal',
                                              $this->arr_rpt_fields[21]=>'normal',
                                              $this->arr_rpt_fields[22]=>'normal',
                                              $this->arr_rpt_fields[23]=>'normal',
                                              $this->arr_rpt_fields[24]=>'normal',
                                              $this->arr_rpt_fields[25]=>'normal',
                                              $this->arr_rpt_fields[26]=>'normal',
                                              $this->arr_rpt_fields[27]=>'normal',
                                              $this->arr_rpt_fields[28]=>'normal',
                                              $this->arr_rpt_fields[29]=>'normal',
                                              $this->arr_rpt_fields[30]=>'normal',
                                              $this->arr_rpt_fields[31]=>'number_format2',
                                              $this->arr_rpt_fields[32]=>'number_format2',
                                              $this->arr_rpt_fields[33]=>'normal',
                                              $this->arr_rpt_fields[34]=>'normal',
                                              $this->arr_rpt_fields[35]=>'normal',
                                              $this->arr_rpt_fields[36]=>'normal',
                                              $this->arr_rpt_fields[37]=>'normal',
                                              $this->arr_rpt_fields[38]=>'normal',
                                              $this->arr_rpt_fields[39]=>'normal',
                                              $this->arr_rpt_fields[40]=>'normal',
                                              $this->arr_rpt_fields[41]=>'normal',
                                              $this->arr_rpt_fields[42]=>'normal',
                                              $this->arr_rpt_fields[43]=>'normal',
                                              $this->arr_rpt_fields[44]=>'normal',
                                              $this->arr_rpt_fields[45]=>'normal',
                                              $this->arr_rpt_fields[46]=>'normal',
                                              $this->arr_rpt_fields[47]=>'normal',
                                              $this->arr_rpt_fields[48]=>'normal',
                                              $this->arr_rpt_fields[49]=>'normal',
                                              $this->arr_rpt_fields[50]=>'normal',
                                              $this->arr_rpt_fields[51]=>'normal',
                                              $this->arr_rpt_fields[52]=>'normal',
                                              $this->arr_rpt_fields[53]=>'normal',
                                              $this->arr_rpt_fields[54]=>'normal',
                                              $this->arr_rpt_fields[55]=>'normal',
                                              $this->arr_rpt_fields[56]=>'normal',
                                              );

        $this->arr_rpt_show_sum = array($this->arr_rpt_fields[0]=>TRUE,
                                        $this->arr_rpt_fields[1]=>FALSE,
                                        $this->arr_rpt_fields[2]=>FALSE,
                                        $this->arr_rpt_fields[3]=>FALSE,
                                        $this->arr_rpt_fields[4]=>FALSE,
                                        $this->arr_rpt_fields[5]=>FALSE,
                                        $this->arr_rpt_fields[6]=>FALSE,
                                        $this->arr_rpt_fields[7]=>FALSE,
                                        $this->arr_rpt_fields[8]=>FALSE,
                                        $this->arr_rpt_fields[9]=>FALSE,
                                        $this->arr_rpt_fields[10]=>FALSE,
                                        $this->arr_rpt_fields[11]=>FALSE,
                                        $this->arr_rpt_fields[12]=>FALSE,
                                        $this->arr_rpt_fields[13]=>FALSE,
                                        $this->arr_rpt_fields[14]=>FALSE,
                                        $this->arr_rpt_fields[15]=>FALSE,
                                        $this->arr_rpt_fields[16]=>FALSE,
                                        $this->arr_rpt_fields[17]=>FALSE,
                                        $this->arr_rpt_fields[18]=>FALSE,
                                        $this->arr_rpt_fields[19]=>FALSE,
                                        $this->arr_rpt_fields[20]=>FALSE,
                                        $this->arr_rpt_fields[21]=>FALSE,
                                        $this->arr_rpt_fields[22]=>FALSE,
                                        $this->arr_rpt_fields[23]=>FALSE,
                                        $this->arr_rpt_fields[24]=>FALSE,
                                        $this->arr_rpt_fields[25]=>FALSE,
                                        $this->arr_rpt_fields[26]=>FALSE,
                                        $this->arr_rpt_fields[27]=>FALSE,
                                        $this->arr_rpt_fields[28]=>FALSE,
                                        $this->arr_rpt_fields[29]=>FALSE,
                                        $this->arr_rpt_fields[30]=>FALSE,
                                        $this->arr_rpt_fields[31]=>TRUE,
                                        $this->arr_rpt_fields[32]=>TRUE,
                                        $this->arr_rpt_fields[33]=>FALSE,
                                        $this->arr_rpt_fields[34]=>FALSE,
                                        $this->arr_rpt_fields[35]=>FALSE,
                                        $this->arr_rpt_fields[36]=>FALSE,
                                        $this->arr_rpt_fields[37]=>FALSE,
                                        $this->arr_rpt_fields[38]=>FALSE,
                                        $this->arr_rpt_fields[39]=>FALSE,
                                        $this->arr_rpt_fields[40]=>FALSE,
                                        $this->arr_rpt_fields[41]=>FALSE,
                                        $this->arr_rpt_fields[42]=>FALSE,
                                        $this->arr_rpt_fields[43]=>FALSE,
                                        $this->arr_rpt_fields[44]=>FALSE,
                                        $this->arr_rpt_fields[45]=>FALSE,
                                        $this->arr_rpt_fields[46]=>FALSE,
                                        $this->arr_rpt_fields[47]=>FALSE,
                                        $this->arr_rpt_fields[48]=>FALSE,
                                        $this->arr_rpt_fields[49]=>FALSE,
                                        $this->arr_rpt_fields[50]=>FALSE,
                                        $this->arr_rpt_fields[51]=>FALSE,
                                        $this->arr_rpt_fields[52]=>FALSE,
                                        $this->arr_rpt_fields[53]=>FALSE,
                                        $this->arr_rpt_fields[54]=>FALSE,
                                        $this->arr_rpt_fields[55]=>FALSE,
                                        $this->arr_rpt_fields[56]=>FALSE,
                                        );
        return $this;
    }
}
