<?php
class required_appointment_dd
{
    static $table_name = 'required_appointment';
    static $readable_name = 'Required Appointment';

    static function load_dictionary()
    {
        $fields = array(
                    'required_appointment_id' => array('value'=>'',
                                          'nullable'=>FALSE,
                                          'data_type'=>'integer',
                                          'length'=>20,
                                          'required'=>FALSE,
                                          'attribute'=>'primary key',
                                          'control_type'=>'none',
                                          'size'=>'60',
                                          'drop_down_has_blank'=>TRUE,
                                          'label'=>'Required Appointment ID',
                                          'extra'=>'',
                                          'companion'=>'',
                                          'in_listview'=>FALSE,
                                          'char_set_method'=>'generate_num_set',
                                          'char_set_allow_space'=>FALSE,
                                          'extra_chars_allowed'=>'-',
                                          'allow_html_tags'=>FALSE,
                                          'trim'=>'trim',
                                          'valid_set'=>array(),
                                          'date_elements'=>array('','',''),
                                          'date_default'=>'',
                                          'list_type'=>'',
                                          'list_settings'=>array(''),
                                          'rpt_in_report'=>TRUE,
                                          'rpt_column_format'=>'normal',
                                          'rpt_column_alignment'=>'center',
                                          'rpt_show_sum'=>TRUE),
                    'student_id' => array('value'=>'',
                                          'nullable'=>FALSE,
                                          'data_type'=>'varchar',
                                          'length'=>11,
                                          'required'=>TRUE,
                                          'attribute'=>'foreign key',
                                          'control_type'=>'drop-down list',
                                          'size'=>'60',
                                          'drop_down_has_blank'=>TRUE,
                                          'label'=>'Student',
                                          'extra'=>'onChange="this.form.submit()"',
                                          'companion'=>'',
                                          'in_listview'=>TRUE,
                                          'char_set_method'=>'',
                                          'char_set_allow_space'=>TRUE,
                                          'extra_chars_allowed'=>'',
                                          'allow_html_tags'=>FALSE,
                                          'trim'=>'trim',
                                          'valid_set'=>array(),
                                          'date_elements'=>array('','',''),
                                          'date_default'=>'',
                                          'list_type'=>'sql generated',
                                          'list_settings'=>array('query' => "SELECT refstudent.student_id AS `Queried_student_id` FROM refstudent ORDER BY `Queried_student_id`",
                                                                     'list_value' => 'Queried_student_id',
                                                                     'list_items' => array('Queried_student_id'),
                                                                     'list_separators' => array()),
                                          'rpt_in_report'=>TRUE,
                                          'rpt_column_format'=>'normal',
                                          'rpt_column_alignment'=>'center',
                                          'rpt_show_sum'=>FALSE),
                    'date' => array('value'=>'',
                                          'nullable'=>FALSE,
                                          'data_type'=>'date',
                                          'length'=>0,
                                          'required'=>TRUE,
                                          'attribute'=>'',
                                          'control_type'=>'date controls',
                                          'size'=>'',
                                          'drop_down_has_blank'=>TRUE,
                                          'label'=>'Date',
                                          'extra'=>'',
                                          'companion'=>'',
                                          'in_listview'=>TRUE,
                                          'char_set_method'=>'',
                                          'char_set_allow_space'=>TRUE,
                                          'extra_chars_allowed'=>'',
                                          'allow_html_tags'=>FALSE,
                                          'trim'=>'trim',
                                          'valid_set'=>array(),
                                          'date_elements'=>array('date_year','date_month','date_day'),
                                          'date_default'=>'',
                                          'list_type'=>'',
                                          'list_settings'=>array(''),
                                          'rpt_in_report'=>TRUE,
                                          'rpt_column_format'=>'normal',
                                          'rpt_column_alignment'=>'left',
                                          'rpt_show_sum'=>FALSE),
                    'time_start' => array('value'=>'',
                                          'nullable'=>FALSE,
                                          'data_type'=>'varchar',
                                          'length'=>2,
                                          'required'=>TRUE,
                                          'attribute'=>'',
                                          'control_type'=>'drop-down list',
                                          'size'=>'5',
                                          'drop_down_has_blank'=>TRUE,
                                          'label'=>'Time Start',
                                          'extra'=>'',
                                          'companion'=>': <select name="minutes"> <option value="00"> 00</option> <option value="01"> 01</option>  <option value="02"> 02</option>  <option value="03"> 03 </option> <option value="04"> 04</option> <option value="05"> 05</option> <option value="06"> 06</option> <option value="07"> 07</option> <option value="08"> 08</option> <option value="09"> 09</option> <option value="10"> 10</option> <option value="11"> 11</option> <option value="12"> 12</option> <option value="13"> 13</option> <option value="14"> 14</option> <option value="15"> 15</option> <option value="16"> 16</option> <option value="17"> 17</option> <option value="18"> 18</option> <option value="19"> 19</option> <option value="20"> 20</option> <option value="21"> 21</option> <option value="22"> 22</option> <option value="23"> 23</option> <option value="24"> 24</option> <option value="25"> 25</option> <option value="26"> 26</option> <option value="27"> 27</option> <option value="28"> 28</option> <option value="29"> 29</option> <option value="30"> 30</option> <option value="31"> 31</option> <option value="32"> 32</option> <option value="33"> 33</option> <option value="34"> 34</option> <option value="35"> 35</option> <option value="36"> 36</option> <option value="37"> 37</option> <option value="38"> 38</option> <option value="39"> 39</option> <option value="40"> 40</option> <option value="41"> 41</option> <option value="42"> 42</option> <option value="43"> 43</option> <option value="44"> 44</option> <option value="45"> 45</option> <option value="46"> 46</option> <option value="47"> 47</option> <option value="48"> 48</option> <option value="49"> 49</option> <option value="50"> 50</option> <option value="51"> 51</option> <option value="52"> 52</option> <option value="53"> 53</option> <option value="54"> 54</option> <option value="55"> 55</option> <option value="56"> 56</option> <option value="57"> 57</option> <option value="58"> 58</option> <option value="59"> 59</option> </select> <select name="ampm"> <option value="AM"> AM</option> <option value="PM"> PM</option> </select>',
                                          'in_listview'=>TRUE,
                                          'char_set_method'=>'generate_num_set',
                                          'char_set_allow_space'=>FALSE,
                                          'extra_chars_allowed'=>': AM PM',
                                          'allow_html_tags'=>FALSE,
                                          'trim'=>'trim',
                                          'valid_set'=>array(),
                                          'date_elements'=>array('','',''),
                                          'date_default'=>'',
                                          'list_type'=>'predefined',
                                          'list_settings'=>array('per_line'=>TRUE,
                                                             'items'  =>array('01','02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12',),
                                                             'values' =>array('01','02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12',)),
                                          'rpt_in_report'=>TRUE,
                                          'rpt_column_format'=>'number_format2',
                                          'rpt_column_alignment'=>'right',
                                          'rpt_show_sum'=>TRUE),
                    'time_end' => array('value'=>'',
                                          'nullable'=>FALSE,
                                          'data_type'=>'varchar',
                                          'length'=>2,
                                          'required'=>TRUE,
                                          'attribute'=>'',
                                          'control_type'=>'drop-down list',
                                          'size'=>'5',
                                          'drop_down_has_blank'=>TRUE,
                                          'label'=>'Time End',
                                          'extra'=>'',
                                          'companion'=>': <select name="minutes2"> <option value="00"> 00</option> <option value="01"> 01</option>  <option value="02"> 02</option>  <option value="03"> 03 </option> <option value="04"> 04</option> <option value="05"> 05</option> <option value="06"> 06</option> <option value="07"> 07</option> <option value="08"> 08</option> <option value="09"> 09</option> <option value="10"> 10</option> <option value="11"> 11</option> <option value="12"> 12</option> <option value="13"> 13</option> <option value="14"> 14</option> <option value="15"> 15</option> <option value="16"> 16</option> <option value="17"> 17</option> <option value="18"> 18</option> <option value="19"> 19</option> <option value="20"> 20</option> <option value="21"> 21</option> <option value="22"> 22</option> <option value="23"> 23</option> <option value="24"> 24</option> <option value="25"> 25</option> <option value="26"> 26</option> <option value="27"> 27</option> <option value="28"> 28</option> <option value="29"> 29</option> <option value="30"> 30</option> <option value="31"> 31</option> <option value="32"> 32</option> <option value="33"> 33</option> <option value="34"> 34</option> <option value="35"> 35</option> <option value="36"> 36</option> <option value="37"> 37</option> <option value="38"> 38</option> <option value="39"> 39</option> <option value="40"> 40</option> <option value="41"> 41</option> <option value="42"> 42</option> <option value="43"> 43</option> <option value="44"> 44</option> <option value="45"> 45</option> <option value="46"> 46</option> <option value="47"> 47</option> <option value="48"> 48</option> <option value="49"> 49</option> <option value="50"> 50</option> <option value="51"> 51</option> <option value="52"> 52</option> <option value="53"> 53</option> <option value="54"> 54</option> <option value="55"> 55</option> <option value="56"> 56</option> <option value="57"> 57</option> <option value="58"> 58</option> <option value="59"> 59</option> </select> <select name="am_pm"> <option value="AM"> AM</option> <option value="PM"> PM</option> </select>',
                                          'in_listview'=>TRUE,
                                          'char_set_method'=>'generate_num_set',
                                          'char_set_allow_space'=>FALSE,
                                          'extra_chars_allowed'=>': AM PM',
                                          'allow_html_tags'=>FALSE,
                                          'trim'=>'trim',
                                          'valid_set'=>array(),
                                          'date_elements'=>array('','',''),
                                          'date_default'=>'',
                                          'list_type'=>'predefined',
                                          'list_settings'=>array('per_line'=>TRUE,
                                                             'items'  =>array('01','02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12',),
                                                             'values' =>array('01','02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12',)),
                                          'rpt_in_report'=>TRUE,
                                          'rpt_column_format'=>'number_format2',
                                          'rpt_column_alignment'=>'right',
                                          'rpt_show_sum'=>TRUE),
                    'status' => array('value'=>'',
                                          'nullable'=>TRUE,
                                          'data_type'=>'varchar',
                                          'length'=>255,
                                          'required'=>TRUE,
                                          'attribute'=>'none',
                                          'control_type'=>'radio buttons',
                                          'size'=>'60',
                                          'drop_down_has_blank'=>TRUE,
                                          'label'=>'Status',
                                          'extra'=>'',
                                          'companion'=>'',
                                          'in_listview'=>TRUE,
                                          'char_set_method'=>'',
                                          'char_set_allow_space'=>TRUE,
                                          'extra_chars_allowed'=>'',
                                          'allow_html_tags'=>FALSE,
                                          'trim'=>'trim',
                                          'valid_set'=>array(),
                                          'date_elements'=>array('','',''),
                                          'date_default'=>'',
                                          'list_type'=>'predefined',
                                          'list_settings'=>array('per_line'=>TRUE,
                                                             'items'  =>array('Completed','Pending'),
                                                             'values' =>array('Completed','Pending')),
                                          'rpt_in_report'=>TRUE,
                                          'rpt_column_format'=>'normal',
                                          'rpt_column_alignment'=>'left',
                                          'rpt_show_sum'=>FALSE)
                   
                       );
        return $fields;
    }

    static function load_relationships()
    {
        $relations = array(array('type'=>'1-1',
                                 'table'=>'refstudent',
                                 'alias'=>'',
                                 'link_parent'=>'student_id',
                                 'link_child'=>'student_id',
                                 'link_subtext'=>array('student_id'),
                                 'where_clause'=>''));

        return $relations;
    }

    static function load_subclass_info()
    {
        $subclasses = array('html_file'=>'required_appointment_html.php',
                            'html_class'=>'required_appointment_html',
                            'data_file'=>'required_appointment.php',
                            'data_class'=>'required_appointment');
        return $subclasses;
    }

}